api: 
  url: https://apptwo.contrastsecurity.com/Contrast
  api_key: 6E6IRUQn6V12wbJ86SWQn8c4nue2QXz7
  service_key: M1D2QNV8MS2S1A2A
  user_name: sergei.bulatov@contrastsecurity.com
application:
  name: Sample
server:
  environment: PRODUCTION
